### ISSUE TITLE
`vi` not working in `1.3-testing`

### ISSUE THREAD

**Issue by th1nhhdk** [hanh-linux/hanh-packages#4]
![image](https://user-images.githubusercontent.com/58503327/143424623-646bb6c3-9821-48ba-b9ba-652d1d016a04.png)

**Comment by hanhlinux** [comment]
This is a `toybox`'s issue, `nano` is installed for this.

**Comment by hanhlinux** [comment]
`vi` code is in pending support in toybox, so it is unstable. Try to create a non-empty text file with `nano` (or `tee` a log) and then `vi` to it.
